### PR TITLE
incrementing and decrementing the data so that 0s display now as 1s

### LINKED ISSUE #138: Change 0->1s, etc
As discussed in #114

### PR DESCRIPTION
**Pull request by samhstn**
Fixes #138

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@shouston3 LGTM. 👀  👍

**Comment by nelsonic** [comment]
@shouston3 what would it take to add a test to cover these last two lines of code? 🤔

**Comment by samhstn** [comment]
We just need to abstract out the function into a separate helper which manages the url to use and get our coverage to ignore this file.

We should be tying up these loose ends today. Added as a separate issue #140

**Comment by nelsonic** [comment]
@shouston3 good plan! 👍 
Would you mind investigating how to setup a pre-commit hook 
to check coverage on localhost `before` a commit is allowed?
see: https://github.com/dwyl/learn-pre-commit/issues/6
(_doesn't have to be **today** but sometime would be awesome!_) ✨

**Comment by samhstn** [comment]
It may not have worked well for us because of the local coverage issue here: https://github.com/dwyl/learn-phoenix-framework/issues/55

Currently, our coverage is never 100% locally

**Pull request merged**
