### PR TITLE
Final Todos

### LINKED ISSUE #161: Final Todos
Todos from #160 

- [x] Add date to top skills wheel so it's clear which one it is
- [x] In PDF download, make answers to info un-bold and increase whitespace between header and skills wheel
- [x] Change title of page to 'Skillswheel'
- [x] Add 'Groups' link to navigation
- [ ] Fix 'Delete group' - gives internal server error
- [x] Add 'Back to groups' button at the bottom of edit group page
#### Admin data:
- [x] Make data headers white background with pink header
- [x] In spreadsheet, show the correct numbers (i.e. 1 instead of 0)
- [ ] In spreadsheet, add new columns ➡️ @iteles

### PR DESCRIPTION
**Pull request by samhstn**
Fixes #161 

All issues should have been addressed except for:
+ Spreadsheet stuff
+ Delete group issue could not be replicated (may have been because of out of date data (database has just been cleared) and should no longer be a problem) (open a new issue if it can be replicated on heroku)

Could you verify the final todos have been addressed https://skillswheel.herokuapp.com/ (I'll flush the Heroku database after this is merged).

@iteles After this is merged, the spreadsheet is updated and the Heroku database is cleared again, are there any more things to do before handing over the app?

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@shouston3 this PR looks good. 
I would suggest that a "Final Todos" should include an update to the README.md
for example a couple of screenshots of the app UI to show what the _end user_ sees.
You could even upload a "walkthrough" to http://gifmaker.me and include a GIF! 😮  😉

**Comment by samhstn** [comment]
@nelsonic Great idea, I'll try to put together a little something like [this](https://github.com/FAC7/anna-freud-hub#final-demo-of-the-ios-app)

**Comment by samhstn** [comment]
Opening a new issue to address readme changes #163

**Review by iteles — APPROVED** [review]
Thanks for these changes @shouston3! Merging and ready for the db flush 👍

**Comment by samhstn** [comment]
@iteles Database is now flushed and I think everything is good to go for Helen.
Also, I've incremented all the cells in the google spreadsheet and set up totals for each section.

**Comment by nelsonic** [comment]
@shouston3 great work! (_well done!_) 😍

**Pull request merged**
